language: ruby
notifications:
  email: true
sudo: false
matrix:
  include:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-3.x
    before_install:
      - gem update --system 2.4.8
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile.rails-4.x
  - rvm: 2.2.4
    gemfile: gemfiles/Gemfile.rails-5.x
    env: ONLY_RAILS=true
